services:
  - type: cron
    name: tm-scraper-alerts
    env: docker
    schedule: "*/20 * * * *"  
    startCommand: "playwright install chromium && python server/cronCheck.py"
    envVars:
      - key: MAILGUN_API_KEY
        sync: false 
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false